language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t rohitkalra/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run  -e CI=true rohitkalra/react-test npm run test -- --coverage
    # - docker run -e CI=true rohitkalra/docker-react npm run test

after_success:
    - docker build -t rohitkalra/multi-client ./client
    - docker build -t rohitkalra/multi-nginx ./nginx
    - docker build -t rohitkalra/multi-server ./server
    - docker build -t rohitkalra/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take images and pushes to docker hub
    - docker push rohitkalra/multi-client
    - docker push rohitkalra/multi-nginx
    - docker push rohitkalra/multi-server
    - docker push rohitkalra/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-730659293973
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

